# Generated by Django 3.2.5 on 2021-08-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210804_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, related_name='_main_product_recommended_products_+', to='main.Product', verbose_name='Рекомендованные продукты'),
        ),
        migrations.AddField(
            model_name='product',
            name='works',
            field=models.ManyToManyField(blank=True, related_name='related_product', to='main.Work', verbose_name='Примеры установки'),
        ),
        migrations.AddField(
            model_name='work',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('works', models.ManyToManyField(blank=True, related_name='related_service', to='main.Work', verbose_name='Работы')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='related_work', to='main.Service', verbose_name='Услуги'),
        ),
    ]
