# Generated by Django 3.2.5 on 2021-08-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210817_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='product',
            name='cocol',
            field=models.CharField(blank=True, max_length=55, verbose_name='Цоколь'),
        ),
        migrations.AddField(
            model_name='product',
            name='cooling',
            field=models.CharField(blank=True, max_length=55, verbose_name='Тип охлаждения'),
        ),
        migrations.AddField(
            model_name='product',
            name='fastening',
            field=models.CharField(blank=True, max_length=55, verbose_name='Тип крепления'),
        ),
        migrations.AddField(
            model_name='product',
            name='flow',
            field=models.CharField(blank=True, max_length=55, verbose_name='Световой поток'),
        ),
        migrations.AddField(
            model_name='product',
            name='gamma',
            field=models.CharField(blank=True, max_length=55, verbose_name='Цветовая гамма'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_obman',
            field=models.BooleanField(default=False, verbose_name='Наличие обманки'),
        ),
        migrations.AddField(
            model_name='product',
            name='high_beam',
            field=models.CharField(blank=True, max_length=55, verbose_name='Дальний свет'),
        ),
        migrations.AddField(
            model_name='product',
            name='ip',
            field=models.CharField(blank=True, max_length=15, verbose_name='IP (степень защиты оболочки)'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_beam',
            field=models.CharField(blank=True, max_length=55, verbose_name='Ближний свет'),
        ),
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, max_length=55, verbose_name='мощность'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=55, verbose_name='ДxШxВ'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_size',
            field=models.CharField(blank=True, max_length=55, verbose_name='Типоразмер'),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AddField(
            model_name='product',
            name='voltage',
            field=models.CharField(blank=True, max_length=55, verbose_name='Напряжение'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='index',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Индекс'),
        ),
    ]
