# Generated by Django 3.2.5 on 2021-08-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210819_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Город'),
        ),
    ]
