# Generated by Django 3.2.5 on 2021-08-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cocol',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cooling',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fastening',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gamma',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_obman',
        ),
        migrations.RemoveField(
            model_name='product',
            name='high_beam',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='product',
            name='low_beam',
        ),
        migrations.RemoveField(
            model_name='product',
            name='power',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='voltage',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, verbose_name='Характеристики'),
        ),
    ]
